apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-rest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-rest
  template:
    metadata:
      labels:
        app: petclinic-rest
    spec:
      containers:
        - name: petclinic-rest
          image: petclinic-rest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9966
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-secret
                  key: SPRING_DATASOURCE_PASSWORD


#  - name: petclinic-rest
#    image: petclinic-rest:latest
#    ports:
#      - containerPort: 9966
