apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-rest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-rest
  template:
    metadata:
      labels:
        app: petclinic-rest
    spec:
      containers:
        - name: petclinic-rest
          image: kleger.azurecr.io/petclinic-rest:latest
          ports:
            - containerPort: 9966
          env:
          - name: SPRING_DATASOURCE_URL
            value: MYSQL_DATABASE
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASS
      imagePullSecrets:
        - name: acr-secret
