name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn clean verify -B

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Spring Boot Actuator Health Check
        run: |
          mvn spring-boot:start
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080/actuator/health
          mvn spring-boot:stop
